version: "3"

volumes:
  db-krispy-ger:

networks:
  net-krispy-ger:

services:
  krispy-kreme-db:
    image: mysql:5.7.33
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    expose:
      - 3306
    volumes:
      - db-krispy-ger:/var/lib/mysql
    networks:
      - net-krispy-ger

  krispy-kreme-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: krispy-kreme-db
    ports:
      - 8080:80
    depends_on:
      - krispy-kreme-db
    networks:
      - net-krispy-ger
